### PR TITLE
CS-192 & CS-147: sidebar doesn't move when scrolling the page

### PR DESCRIPTION
**Pull request by jelevoir**
No position:absolute.
I couldn't remember off the top of my head what I had done during class to get it working.
This was it.

### CODE REVIEW

**Comment by jelevoir** [comment]
Takes care of #192 and #147.

**Comment by ghost** [comment]
Getting some serious overlap on small screen sizes before they shrink down all the way to mobile.
capture
capture2

**Comment by jelevoir** [comment]
@dcfreema 
Check to makes sure the branch is updated.
I push an update to it at 1pm yesterday that should have fixed that.

**Comment by jelevoir** [comment]
@dcfreema 
Never mind. I'm seeing it now.

**Comment by jelevoir** [comment]
@dcfreema 
Fixed. Try it out!

**Comment by bpowell** [comment]
selection_034 I don't see any text unless I hover over the drinks or highlight the entire page

**Comment by jelevoir** [comment]
@bpowell 
Should be good now.

**Pull request merged**
