### PR TITLE
Cs 135

### PR DESCRIPTION
**Pull request by bpowell**
Okay... a drink order can be placed. The UI will need some heavy clean up. I want to get this merged so we can start testing it and find all the ugly bugs. Right now there is no success message if the order is properly added. Nor is there an error message for a failure. You will have to check the database for that. Also that will have to be implemented in javascript (the success message that is). This one is kind of messy. But it is a start. Once this is merged, we can create other issues to fix all the problems listed above. If there are other problems, let me know and I will update this PR.

### CODE REVIEW

**Comment by bpowell** [comment]
I forgot one thing, that is drink count. Right now it is assumed to be one. Once we figure out a better UI, we can add a field for that. So I'm not counting that as an issue to fix in this PR.

**Comment by jelevoir** [comment]
So I'm encountering a few bugs with this one.
About 1/2 of the drinks work as intended.
The ones that are broken are not showing the 'quick order button' and bring up the wrong drink in the modal. But, if you click on 'order drink'  button within the modal, it will order the drink originally clicked on and not the one mistakenly shown in the modal.

I'm looking into it right now, but I'm not sure I want to merge into master at this point. I'm going to play around with this branch.

**Comment by bpowell** [comment]
Yeah... I know. That's why I wanted to get this looked at by others before I got too far. Let me know what you find. I'll take a look at that issue in a few.

**Comment by bpowell** [comment]
@jelevoir can you upload your testing sql file so I can test with the same data as you.

**Comment by jelevoir** [comment]
Sure. I'll upload it to the docs folder as soon as I get home from work.

**Comment by jelevoir** [comment]
I uploaded my test SQL commands.

**Comment by bpowell** [comment]
I think I got the issue that you had fixed. Try it out and let me know.

**Pull request merged**
