### PR TITLE
Fix button appearance and add hover style #96 #97

### PR DESCRIPTION
**Pull request by ghost**
I was able to tackle two issues together, I think this makes the navbar look WAY more modern.

capture

### CODE REVIEW

**Comment by jelevoir** [comment]
I'm getting a "bobbing" happening when I hover over a button.
This is due to the buttons not having a border on top before hovering, and having a 2px border afterwards. 

Due to the way the header is constructed, it causes the main header div (with id "headerContent") to grow when a button is hovered over.

**Comment by ghost** [comment]
Good catch, will fix.

**Comment by ghost** [comment]
@jelevoir should be fixed now

**Comment by bpowell** [comment]
I'll let @jelevoir merge this one! :)

**Comment by ghost** [comment]
Merging my own otherwise it will cause a conflict

**Pull request merged**
