### PR TITLE
Cs 161

### PR DESCRIPTION
**Pull request by bpowell**
Oh man, this is an interesting one. I had to have the javascript be in a JSP file so Spring security can do injections for sec:authorize access and passing the bar id to the API. Right now it has 15 drinks per page, with a crappy looking Previous/Next link (which calls some fancy javascript). Those links will have to fixed to make them look pretty. I don't plan on adding like a page numbering system. I think that would be too much work. This should do it.

### CODE REVIEW

**Comment by bpowell** [comment]
Don't merge just yet, I think I can add the page numbering system easily.

**Comment by bpowell** [comment]
Okay! Go ahead and merge. Didn't take long at all

**Comment by jelevoir** [comment]
Couple things. Not sure what you want to do about it.
When I was doing testing, I found that if there are 15 drinks at the bar it will still show two pages, with the second being empty.
Also drink images are not showing up.

**Comment by bpowell** [comment]
Drink images are from the database. So you would need a valid icon url for them. We can change that and drop the icon url thing or do something different. If you could, can you merge it anyway and make an issue about the multiple pages. I need this for adding drinks.

**Pull request merged**
