### PR TITLE
Cs 117

### PR DESCRIPTION
**Pull request by bpowell**
@jelevoir can you take a look at this one. Don't worry about the merge right now. But I'm hitting a bug when I try to remove a drink from a bar. On the right hand side, there will be a list of all drinks that the bar currently has. If you click on it, a modal pops up. In the modal you can either close or remove the drink. When you try to remove the drink, the drink goes away but the modal closes IMPROPERLY! If you could help me figure this one out, that would be great.

### CODE REVIEW

**Comment by bpowell** [comment]
@jelevoir I fixed the issue of when you try to remove the drink, the drink goes away but the modal closes IMPROPERLY! I solved that by doing a page refresh after you remove the drink. It is a bit hacky, but it totally works - and I'm okay with that.

Once you test this out, I can do the merge cause it looks like there are conflicts on something.

**Comment by jelevoir** [comment]
So I fixed the success message.
So, you know how you have that refresh hack after removing a drink?
I think you should add that after adding a drink as well. 
When you click on a drink to add that isn't a part of the bar, the user can click on add drink multiple times and it will add duplicates for each drink.
If we add the refresh, it should eliminate that problem.
Thoughts?

**Comment by bpowell** [comment]
Works for me! I can add that real quick.

**Comment by bpowell** [comment]
Page now reloads when adding a drink. Let me know how it all works.

**Comment by jelevoir** [comment]
Success! It works.
I think it's good to go.
I made one final change. Nothing that needs testing.
Feel free to merge.

**Comment by bpowell** [comment]
Okay cool beans, will do after dinner!

**Pull request merged**
